# Generated by Django 2.1 on 2019-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('stand', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
